### PR TITLE
Fix gallery posts

### PR DESCRIPTION
**Pull request by floorish**
Gallery posts do not load anymore. This PR restores the gallery functionality by extracting the image urls from the comments page.

**Steps to reproduce:**
1. Open any "Open gallery media" post

**Expected:**
- Gallery media loads and shows images

**Observed:**
- Gallery post keeps loading and doesn't show any images

Unfortunately it looks like the reddit gallery page body (`reddit.com/gallery/xxxxxxx`) has changed and does not contain any img urls anymore (originally: `ul li a`)

This page has a custom redirect to the comments page (`/r/subreddit/comments/xxxxxxx/the_post_name/`), which contains the images. The redirect is done in js, which is not automatically followed using `URLSession.shared.dataTask`.

Therefore the relative redirect url is extracted from the gallery page body (`<shreddit-redirect href="/r/comments/xxxxxxx/the_post_name">`) which is then loaded to extract image urls.

The image urls are extracted from the `<gallery-carousel>` component.

1. Load `reddit.com/gallery/xxxxxxx`
2. Parse body and extract `href` of `<shreddit-redirect>` 
3. Load  the new url
4. Parse body and extract image urls from `<gallery-carousel>`

Pretty fragile and this will break again when the underlying html changes, but that is probably inevitable. Not sure if there is a better method than manually following the redirect, but this seems to work for now.

### CODE REVIEW

**Comment by floorish** [comment]
I just saw that this is already fixed in commit `7a2fb0c` oops! That seems like a simpler solution. You can close this if it's not necessary anymore :)

**Comment by ejbills** [comment]
Yessir, fixed this last night. Thanks for the PR regardless, I appreciate the ongoing maintenance support!

**Comment by ejbills** [comment]
FYI, I will be pushing a new version of Artemis to the app store today. If you have anything you want included, let me know and I can wait to get your additions added.

**Comment by floorish** [comment]
Awesome, thanks! Using the app daily :)

I noticed that scrolling is a bit wonky when building with Xcode 16 — is that something you've noticed as well? Particularly when scrolling towards loading a new posts page, it seems to suddenly overshoot causing a flash of a blank screen. Sometimes it even scrolls all the way to the top. It's inconsistent and not sure if it's just the debug build, but it doesn't happen when building with Xcode 15.

**Comment by ejbills** [comment]
I noticed this too and had to postpone the app store release as I was trying to fix this last night. I will just build it with Xcode 15 for now, thanks for bringing that workaround to my attention! I think it's a swift ui bug.

**Pull request closed without merging**
